# Autogenerated wrapper script for Xorg_libX11_jll for armv6l-linux-gnueabihf
export libX11, libX11_xcb

using Xorg_libxcb_jll
using Xorg_xtrans_jll
JLLWrappers.@generate_wrapper_header("Xorg_libX11")
JLLWrappers.@declare_library_product(libX11, "libX11.so.6")
JLLWrappers.@declare_library_product(libX11_xcb, "libX11-xcb.so.1")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libxcb_jll, Xorg_xtrans_jll)
    JLLWrappers.@init_library_product(
        libX11,
        "lib/libX11.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libX11_xcb,
        "lib/libX11-xcb.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
