# Autogenerated wrapper script for libaom_jll for aarch64-apple-darwin
export aomdec, aomenc, libaom

JLLWrappers.@generate_wrapper_header("libaom")
JLLWrappers.@declare_library_product(libaom, "@rpath/libaom.3.dylib")
JLLWrappers.@declare_executable_product(aomdec)
JLLWrappers.@declare_executable_product(aomenc)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libaom,
        "lib/libaom.3.13.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        aomdec,
        "bin/aomdec",
    )

    JLLWrappers.@init_executable_product(
        aomenc,
        "bin/aomenc",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
