# Autogenerated wrapper script for libvorbis_jll for aarch64-apple-darwin
export libvorbis, libvorbisenc, libvorbisfile

using Ogg_jll
JLLWrappers.@generate_wrapper_header("libvorbis")
JLLWrappers.@declare_library_product(libvorbis, "@rpath/libvorbis.0.dylib")
JLLWrappers.@declare_library_product(libvorbisenc, "@rpath/libvorbisenc.2.dylib")
JLLWrappers.@declare_library_product(libvorbisfile, "@rpath/libvorbisfile.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Ogg_jll)
    JLLWrappers.@init_library_product(
        libvorbis,
        "lib/libvorbis.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libvorbisenc,
        "lib/libvorbisenc.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libvorbisfile,
        "lib/libvorbisfile.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
