# Autogenerated wrapper script for libvorbis_jll for aarch64-linux-musl
export libvorbis, libvorbisenc, libvorbisfile

using Ogg_jll
JLLWrappers.@generate_wrapper_header("libvorbis")
JLLWrappers.@declare_library_product(libvorbis, "libvorbis.so.0")
JLLWrappers.@declare_library_product(libvorbisenc, "libvorbisenc.so.2")
JLLWrappers.@declare_library_product(libvorbisfile, "libvorbisfile.so.3")
function __init__()
    JLLWrappers.@generate_init_header(Ogg_jll)
    JLLWrappers.@init_library_product(
        libvorbis,
        "lib/libvorbis.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libvorbisenc,
        "lib/libvorbisenc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libvorbisfile,
        "lib/libvorbisfile.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
