name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags: '*'

# Needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  climadiagnostics:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '1.10'
          - '1.11'
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@latest
      - uses: codecov/codecov-action@v5
        if: ${{ matrix.version == '1.10' }}
        with:
          files: lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Archive production artifacts
        if: ${{ matrix.version == '1.10' }}
        uses: actions/upload-artifact@v4
        with:
          name: flamegraphs
          path: |
            test/*.html
