# Autogenerated wrapper script for JuliaNVTXCallbacks_jll for aarch64-linux-gnu
export libjulia_nvtx_callbacks

JLLWrappers.@generate_wrapper_header("JuliaNVTXCallbacks")
JLLWrappers.@declare_library_product(libjulia_nvtx_callbacks, "libjulia_nvtx_callbacks.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libjulia_nvtx_callbacks,
        "lib/libjulia_nvtx_callbacks.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
