# Autogenerated wrapper script for JuliaNVTXCallbacks_jll for x86_64-w64-mingw32
export libjulia_nvtx_callbacks

JLLWrappers.@generate_wrapper_header("JuliaNVTXCallbacks")
JLLWrappers.@declare_library_product(libjulia_nvtx_callbacks, "libjulia_nvtx_callbacks.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libjulia_nvtx_callbacks,
        "bin\\libjulia_nvtx_callbacks.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
