# Autogenerated wrapper script for Rmath_jll for i686-w64-mingw32
export libRmath

JLLWrappers.@generate_wrapper_header("Rmath")
JLLWrappers.@declare_library_product(libRmath, "libRmath-julia.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libRmath,
        "bin\\libRmath-julia.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
