# Autogenerated wrapper script for Expat_jll for x86_64-w64-mingw32
export libexpat, xmlwf

JLLWrappers.@generate_wrapper_header("Expat")
JLLWrappers.@declare_library_product(libexpat, "libexpat-1.dll")
JLLWrappers.@declare_executable_product(xmlwf)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libexpat,
        "bin\\libexpat-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        xmlwf,
        "bin\\xmlwf.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
