# Autogenerated wrapper script for Ogg_jll for aarch64-apple-darwin
export libogg

JLLWrappers.@generate_wrapper_header("Ogg")
JLLWrappers.@declare_library_product(libogg, "@rpath/libogg.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libogg,
        "lib/libogg.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
