# Autogenerated wrapper script for Graphite2_jll for x86_64-w64-mingw32
export libgraphite2

JLLWrappers.@generate_wrapper_header("Graphite2")
JLLWrappers.@declare_library_product(libgraphite2, "libgraphite2.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgraphite2,
        "bin\\libgraphite2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
