# Autogenerated wrapper script for Giflib_jll for aarch64-apple-darwin
export libgif

JLLWrappers.@generate_wrapper_header("Giflib")
JLLWrappers.@declare_library_product(libgif, "@rpath/libgif.7.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgif,
        "lib/libgif.7.2.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
