# Autogenerated wrapper script for Giflib_jll for i686-w64-mingw32
export libgif

JLLWrappers.@generate_wrapper_header("Giflib")
JLLWrappers.@declare_library_product(libgif, "libgif-7.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libgif,
        "bin\\libgif-7.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
