# Autogenerated wrapper script for Xorg_libpciaccess_jll for x86_64-unknown-freebsd
export libpciaccess

using Zlib_jll
JLLWrappers.@generate_wrapper_header("Xorg_libpciaccess")
JLLWrappers.@declare_library_product(libpciaccess, "libpciaccess.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll)
    JLLWrappers.@init_library_product(
        libpciaccess,
        "lib/libpciaccess.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
