name: Unit test

on:
  create:
    tags:
  push:
    branches: [master]
  pull_request:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
        os: [ubuntu-latest, windows-latest]
        arch: [x64]
        include:
          - os: macOS-latest
            julia-version: '1'
            arch: aarch64
          - os: ubuntu-latest
            julia-version: '1'
            arch: x86
          - os: ubuntu-latest
            julia-version: 'min'
            arch: x64

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@latest
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
