name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags: '*'
  merge_group:
concurrency:
  # Skip intermediate builds: all builds except for builds on the `main` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
permissions:
  contents: read
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.0' # First LTS
          - '1.1' # TODO: delete this line
          - '1.2' # TODO: delete this line
          - '1.3' # Not an LTS, but a popular lower bound in the ecosystem, due to Artifacts
          - '1.4' # TODO: delete this line
          - '1.5' # TODO: delete this line
          - '1.6' # Second LTS
          - '1.7' # TODO: delete this line
          - '1.8' # TODO: delete this line
          - '1.9' # TODO: delete this line
          - '1' # automatically expands to latest stable 1.x release of Julia
          - 'nightly'
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@ac0d62164df5a47de404f4e96ce86a1a28a28d56
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/julia-buildpkg@e3eb439fad4f9aba7da2667e7510e4a46ebc46e1
      - uses: julia-actions/julia-runtest@1e03e0122a598a569004c1e26950e2547b350ec0
      - uses: julia-actions/julia-processcoverage@03114f09f119417c3242a9fb6e0b722676aedf38
      - uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
