# Autogenerated wrapper script for libfdk_aac_jll for aarch64-apple-darwin
export libfdk

JLLWrappers.@generate_wrapper_header("libfdk_aac")
JLLWrappers.@declare_library_product(libfdk, "@rpath/libfdk-aac.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfdk,
        "lib/libfdk-aac.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
