# Autogenerated wrapper script for SCS_jll for x86_64-unknown-freebsd
export libscsdir, libscsindir

using libblastrampoline_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("SCS")
JLLWrappers.@declare_library_product(libscsdir, "libscsdir.so")
JLLWrappers.@declare_library_product(libscsindir, "libscsindir.so")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libscsdir,
        "lib/libscsdir.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libscsindir,
        "lib/libscsindir.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
