# Autogenerated wrapper script for NVTX_jll for x86_64-w64-mingw32
export libnvToolsExt

JLLWrappers.@generate_wrapper_header("NVTX")
JLLWrappers.@declare_library_product(libnvToolsExt, "libnvToolsExt.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libnvToolsExt,
        "bin\\libnvToolsExt.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
