# Autogenerated wrapper script for Xorg_libXau_jll for aarch64-linux-gnu
export libXau

JLLWrappers.@generate_wrapper_header("Xorg_libXau")
JLLWrappers.@declare_library_product(libXau, "libXau.so.6")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libXau,
        "lib/libXau.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
