# Autogenerated wrapper script for Xorg_libxcb_jll for armv7l-linux-gnueabihf
export libxcb, libxcb_composite, libxcb_damage, libxcb_dpms, libxcb_dri2, libxcb_dri3, libxcb_glx, libxcb_present, libxcb_randr, libxcb_record, libxcb_render, libxcb_res, libxcb_screensaver, libxcb_shape, libxcb_shm, libxcb_sync, libxcb_xf86dri, libxcb_xfixes, libxcb_xinerama, libxcb_xinput, libxcb_xkb, libxcb_xtest, libxcb_xv, libxcb_xvmc

using Xorg_libXau_jll
using Xorg_libXdmcp_jll
JLLWrappers.@generate_wrapper_header("Xorg_libxcb")
JLLWrappers.@declare_library_product(libxcb, "libxcb.so.1")
JLLWrappers.@declare_library_product(libxcb_composite, "libxcb-composite.so.0")
JLLWrappers.@declare_library_product(libxcb_damage, "libxcb-damage.so.0")
JLLWrappers.@declare_library_product(libxcb_dpms, "libxcb-dpms.so.0")
JLLWrappers.@declare_library_product(libxcb_dri2, "libxcb-dri2.so.0")
JLLWrappers.@declare_library_product(libxcb_dri3, "libxcb-dri3.so.0")
JLLWrappers.@declare_library_product(libxcb_glx, "libxcb-glx.so.0")
JLLWrappers.@declare_library_product(libxcb_present, "libxcb-present.so.0")
JLLWrappers.@declare_library_product(libxcb_randr, "libxcb-randr.so.0")
JLLWrappers.@declare_library_product(libxcb_record, "libxcb-record.so.0")
JLLWrappers.@declare_library_product(libxcb_render, "libxcb-render.so.0")
JLLWrappers.@declare_library_product(libxcb_res, "libxcb-res.so.0")
JLLWrappers.@declare_library_product(libxcb_screensaver, "libxcb-screensaver.so.0")
JLLWrappers.@declare_library_product(libxcb_shape, "libxcb-shape.so.0")
JLLWrappers.@declare_library_product(libxcb_shm, "libxcb-shm.so.0")
JLLWrappers.@declare_library_product(libxcb_sync, "libxcb-sync.so.1")
JLLWrappers.@declare_library_product(libxcb_xf86dri, "libxcb-xf86dri.so.0")
JLLWrappers.@declare_library_product(libxcb_xfixes, "libxcb-xfixes.so.0")
JLLWrappers.@declare_library_product(libxcb_xinerama, "libxcb-xinerama.so.0")
JLLWrappers.@declare_library_product(libxcb_xinput, "libxcb-xinput.so.0")
JLLWrappers.@declare_library_product(libxcb_xkb, "libxcb-xkb.so.1")
JLLWrappers.@declare_library_product(libxcb_xtest, "libxcb-xtest.so.0")
JLLWrappers.@declare_library_product(libxcb_xv, "libxcb-xv.so.0")
JLLWrappers.@declare_library_product(libxcb_xvmc, "libxcb-xvmc.so.0")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libXau_jll, Xorg_libXdmcp_jll)
    JLLWrappers.@init_library_product(
        libxcb,
        "lib/libxcb.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_composite,
        "lib/libxcb-composite.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_damage,
        "lib/libxcb-damage.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_dpms,
        "lib/libxcb-dpms.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_dri2,
        "lib/libxcb-dri2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_dri3,
        "lib/libxcb-dri3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_glx,
        "lib/libxcb-glx.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_present,
        "lib/libxcb-present.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_randr,
        "lib/libxcb-randr.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_record,
        "lib/libxcb-record.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_render,
        "lib/libxcb-render.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_res,
        "lib/libxcb-res.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_screensaver,
        "lib/libxcb-screensaver.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_shape,
        "lib/libxcb-shape.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_shm,
        "lib/libxcb-shm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_sync,
        "lib/libxcb-sync.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_xf86dri,
        "lib/libxcb-xf86dri.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_xfixes,
        "lib/libxcb-xfixes.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_xinerama,
        "lib/libxcb-xinerama.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_xinput,
        "lib/libxcb-xinput.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_xkb,
        "lib/libxcb-xkb.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_xtest,
        "lib/libxcb-xtest.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_xv,
        "lib/libxcb-xv.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libxcb_xvmc,
        "lib/libxcb-xvmc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
