# Autogenerated wrapper script for x264_jll for i686-w64-mingw32
export libx264, x264

JLLWrappers.@generate_wrapper_header("x264")
JLLWrappers.@declare_library_product(libx264, "libx264-164.dll")
JLLWrappers.@declare_executable_product(x264)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libx264,
        "bin\\libx264-164.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        x264,
        "bin\\x264.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
