agents:
  queue: central
  modules: julia/1.10.0 cuda/12.2 ucx/1.14.1_cuda-12.2 openmpi/4.1.5_cuda-12.2 nsight-systems/2023.3.1

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  JULIA_NVTX_CALLBACKS: gc
  JULIA_CPU_TARGET: 'broadwell;skylake'
  OPENBLAS_NUM_THREADS: 1
  OMPI_MCA_opal_warn_on_missing_libcuda: 0
  SLURM_KILL_BAD_EXIT: 1
  JULIA_CUDA_MEMORY_POOL: none
  JULIA_MPI_HAS_CUDA: "true"
  MPITRAMPOLINE_LIB: "/groups/esm/software/MPIwrapper/ompi4.1.5_cuda-12.2/lib64/libmpiwrapper.so"
  MPITRAMPOLINE_MPIEXEC: "/groups/esm/software/MPIwrapper/ompi4.1.5_cuda-12.2/bin/mpiwrapperexec"

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate experiments"
      - "julia --project=experiments -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=experiments -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate lib/ClimaLandSimulations"
      - "julia --project=lib/ClimaLandSimulations -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=lib/ClimaLandSimulations -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate test"
      - "julia --project=test -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=test -e 'using Pkg; Pkg.status()'"
    agents:
      slurm_cpus_per_task: 8
      slurm_mem_per_cpu: 8G
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Experiments"
    steps:
      - label: "Richards comparison to Bonan"
        command: "julia --color=yes --project=experiments experiments/standalone/Soil/richards_comparison.jl"
        artifact_paths: "experiments/standalone/Soil/comparison*png"

      - label: "Evaporation from sand"
        command: "julia --color=yes --project=experiments experiments/standalone/Soil/evaporation.jl"
        artifact_paths: "experiments/standalone/Soil/evaporation*png"

      - label: "vaira_test"
        command: "julia --color=yes --project=experiments experiments/integrated/fluxnet/run_fluxnet.jl US-Var"
        artifact_paths: "experiments/integrated/fluxnet/US-Var/out/*png"

      - label: "ozark_test"
        command: "julia --color=yes --project=experiments experiments/integrated/fluxnet/run_fluxnet.jl US-MOz"
        artifact_paths: "experiments/integrated/fluxnet/US-MOz/out/*png"

      - label: "niwot_test"
        command: "julia --color=yes --project=experiments experiments/integrated/fluxnet/run_fluxnet.jl US-NR1"
        artifact_paths: "experiments/integrated/fluxnet/US-NR1/out/*png"

      - label: "harvard_test"
        command: "julia --color=yes --project=experiments experiments/integrated/fluxnet/run_fluxnet.jl US-Ha1"
        artifact_paths: "experiments/integrated/fluxnet/US-Ha1/out/*png"

      - label: "ozark_conservation"
        command: "julia --color=yes --project=experiments experiments/integrated/ozark/conservation/ozark_conservation.jl"
        artifact_paths: "experiments/integrated/ozark/conservation/*png"

      - label: "Soilbiogeochem"
        command: "julia --color=yes --project=experiments experiments/standalone/Biogeochemistry/experiment.jl"

      - label: "Water conservation"
        command: "julia --color=yes --project=experiments experiments/standalone/Soil/water_conservation.jl"
        artifact_paths: "experiments/standalone/Soil/water_conservation*png"

  - group: "ClimaLandSimulations"
    steps:
      - label: "Ozark figures Makie"
        command: "julia --color=yes --project=lib/ClimaLandSimulations lib/ClimaLandSimulations/experiments/ozark.jl"
        artifact_paths: "figures/*pdf"

  - group: "CPU: global bucket"
    steps:
      - label: "Global Bucket on CPU (functional albedo)"
        key: "global_bucket_function_cpu"
        command: "julia --color=yes --project=experiments experiments/standalone/Bucket/global_bucket_function.jl"
        artifact_paths: "experiments/standalone/Bucket/artifacts/*cpu*"

      - label: "Global Bucket on CPU (static map albedo)"
        key: "global_bucket_staticmap_cpu"
        command: "julia --color=yes --project=experiments experiments/standalone/Bucket/global_bucket_staticmap.jl"
        artifact_paths: "experiments/standalone/Bucket/artifacts_staticmap/*cpu*"

      - label: "Global Bucket on CPU (temporal map albedo)"
        key: "global_bucket_temporalmap_cpu"
        command: "julia --color=yes --project=experiments experiments/standalone/Bucket/global_bucket_temporalmap.jl"
        artifact_paths: "experiments/standalone/Bucket/artifacts_temporalmap/*cpu*"

  - group: "GPU: unit tests and global bucket"
    steps:
      - label: "GPU runtests"
        command: "julia --color=yes --project=test test/runtests.jl"
        agents:
          slurm_mem_per_cpu: 8G
          slurm_gpus: 1

      - label: "Global Bucket on GPU (functional albedo)"
        key: "global_bucket_function_gpu"
        command: "julia --color=yes --project=experiments experiments/standalone/Bucket/global_bucket_function.jl"
        agents:
          slurm_mem: 8G
          slurm_gpus: 1
        artifact_paths: "experiments/standalone/Bucket/artifacts/*gpu*"

      - label: "Global Bucket on GPU (static map albedo)"
        key: "global_bucket_staticmap_gpu"
        command: "julia --color=yes --project=experiments experiments/standalone/Bucket/global_bucket_staticmap.jl"
        agents:
          slurm_mem: 8G
          slurm_gpus: 1
        artifact_paths: "experiments/standalone/Bucket/artifacts_staticmap/*gpu*"

      - label: "Global Bucket on GPU (temporal map albedo)"
        key: "global_bucket_temporalmap_gpu"
        command: "julia --color=yes --project=experiments experiments/standalone/Bucket/global_bucket_temporalmap.jl"
        agents:
          slurm_mem: 8G
          slurm_gpus: 1
        artifact_paths: "experiments/standalone/Bucket/artifacts_temporalmap/*gpu*"

  - group: "CPU/GPU comparisons"
    steps:
      - label: "Compare GPU bucket with CPU bucket (functional albedo)"
        command: "julia --color=yes --project=experiments experiments/standalone/Bucket/compare_gpu_cpu_output.jl"
        depends_on:
          - "global_bucket_function_cpu"
          - "global_bucket_function_gpu"

      - label: "Compare GPU bucket with CPU bucket (static map albedo)"
        command: "julia --color=yes --project=experiments experiments/standalone/Bucket/compare_gpu_cpu_output.jl"
        depends_on:
          - "global_bucket_staticmap_cpu"
          - "global_bucket_staticmap_gpu"

      - label: "Compare GPU bucket with CPU bucket (temporal map albedo)"
        command: "julia --color=yes --project=experiments experiments/standalone/Bucket/compare_gpu_cpu_output.jl"
        depends_on:
          - "global_bucket_temporalmap_cpu"
          - "global_bucket_temporalmap_gpu"

  - wait

  - command: "compact_depot"
