# Autogenerated wrapper script for LZO_jll for aarch64-apple-darwin
export liblzo2

JLLWrappers.@generate_wrapper_header("LZO")
JLLWrappers.@declare_library_product(liblzo2, "@rpath/liblzo2.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblzo2,
        "lib/liblzo2.2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
