# Autogenerated wrapper script for LZO_jll for x86_64-w64-mingw32
export liblzo2

JLLWrappers.@generate_wrapper_header("LZO")
JLLWrappers.@declare_library_product(liblzo2, "liblzo2-2.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblzo2,
        "bin\\liblzo2-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
