# Autogenerated wrapper script for Xorg_libXext_jll for x86_64-linux-musl
export libXext

using Xorg_libX11_jll
JLLWrappers.@generate_wrapper_header("Xorg_libXext")
JLLWrappers.@declare_library_product(libXext, "libXext.so.6")
function __init__()
    JLLWrappers.@generate_init_header(Xorg_libX11_jll)
    JLLWrappers.@init_library_product(
        libXext,
        "lib/libXext.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
