# Autogenerated wrapper script for OpenSSL_jll for x86_64-w64-mingw32
export libcrypto, libssl, openssl

JLLWrappers.@generate_wrapper_header("OpenSSL")
JLLWrappers.@declare_library_product(libcrypto, "libcrypto-3-x64.dll")
JLLWrappers.@declare_library_product(libssl, "libssl-3-x64.dll")
JLLWrappers.@declare_executable_product(openssl)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libcrypto,
        "bin\\libcrypto-3-x64.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libssl,
        "bin\\libssl-3-x64.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        openssl,
        "bin\\openssl.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
