# Autogenerated wrapper script for FFTW_jll for aarch64-apple-darwin
export libfftw3, libfftw3f

JLLWrappers.@generate_wrapper_header("FFTW")
JLLWrappers.@declare_library_product(libfftw3, "@rpath/libfftw3.3.dylib")
JLLWrappers.@declare_library_product(libfftw3f, "@rpath/libfftw3f.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfftw3,
        "lib/libfftw3.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfftw3f,
        "lib/libfftw3f.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
