# Autogenerated wrapper script for FFTW_jll for x86_64-w64-mingw32
export libfftw3, libfftw3f

JLLWrappers.@generate_wrapper_header("FFTW")
JLLWrappers.@declare_library_product(libfftw3, "libfftw3-3.dll")
JLLWrappers.@declare_library_product(libfftw3f, "libfftw3f-3.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfftw3,
        "bin\\libfftw3-3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfftw3f,
        "bin\\libfftw3f-3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
