# Autogenerated wrapper script for Opus_jll for x86_64-w64-mingw32
export libopus

JLLWrappers.@generate_wrapper_header("Opus")
JLLWrappers.@declare_library_product(libopus, "libopus-0.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libopus,
        "bin\\libopus-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
