name: CI

on:
  push:
    branches: [main, master]
    tags: ["*"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version:
          - '1'
          - 'lts'
          - 'pre'
      fail-fast: false
    name: Test Julia ${{ matrix.julia-version }}
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          file: ./lcov.info
          flags: Pkg.test
          name: codecov-umbrella

  documenter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v2
      - uses: julia-actions/cache@v2

      - name: Install Run.jl
        run: julia -e 'using Pkg; Pkg.add(name="Run", version="0.1")'
      - name: Install dependencies
        run: julia -e 'using Run; Run.prepare_docs()'
      - name: Build and deploy
        id: build-and-deploy
        if: |
          github.event_name == 'push' || (
            github.event_name == 'pull_request' &&
            !contains(github.head_ref, 'create-pull-request/')
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.SSH_KEY }}
        run: julia -e 'using Run; Run.docs()'
      - name: Just build
        if: steps.build-and-deploy.outcome == 'skipped'
        run: julia -e 'using Run; Run.docs()'

  # A job that succeeds if and only if all jobs succeed.
  all-success:
    if: always() && github.event.pull_request
    needs: [test, documenter]
    runs-on: ubuntu-latest
    steps:
      # https://github.com/tkf/merge-conclusions-action
      - uses: tkf/merge-conclusions-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
