# Autogenerated wrapper script for libass_jll for x86_64-w64-mingw32
export libass

using FreeType2_jll
using FriBidi_jll
using HarfBuzz_jll
using Bzip2_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("libass")
JLLWrappers.@declare_library_product(libass, "libass-9.dll")
function __init__()
    JLLWrappers.@generate_init_header(FreeType2_jll, FriBidi_jll, HarfBuzz_jll, Bzip2_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libass,
        "bin\\libass-9.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
