# Autogenerated wrapper script for isoband_jll for aarch64-apple-darwin
export libisoband

JLLWrappers.@generate_wrapper_header("isoband")
JLLWrappers.@declare_library_product(libisoband, "@rpath/libisoband.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libisoband,
        "lib/libisoband.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
