# Autogenerated wrapper script for isoband_jll for armv6l-linux-musleabihf
export libisoband

JLLWrappers.@generate_wrapper_header("isoband")
JLLWrappers.@declare_library_product(libisoband, "libisoband.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libisoband,
        "lib/libisoband.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
