agents:
  queue: clima
  slurm_mem: 8G
  modules: climacommon/2025_05_15

env:
  JULIA_CUDA_MEMORY_POOL: "cuda"

# We check for the existence of `LONGER_RUN` to determine whether a `LONGER_RUN`
# of `snowy_land.jl`. If you want to do a very long run on Buildkite manually,
# then make a new build and pass `LONGER_RUN=""` as an environment variable. If
# you want to do a very long run locally, you can enter `export LONGER_RUN=""`
# in the terminal and run
# `julia --color=yes --project=.buildkite experiments/long_runs/snowy_land.jl`.
# In both cases, the value of `LONGER_RUN` does not matter.

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate"

      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - julia --project=.buildkite -e 'using Pkg; Pkg.instantiate(;verbose=true)'
      - julia --project=.buildkite -e 'using Pkg; Pkg.precompile()'
      - julia --project=.buildkite -e 'using CUDA; CUDA.precompile_runtime()'
      - julia --project=.buildkite -e 'using Pkg; Pkg.status()'

    agents:
      slurm_gpus: 1
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Global Land Models"
    if: build.env("LONGER_RUN") == null && build.env("PERTURBED_RUN") == null
    steps:

      - label: ":snow_capped_mountain: Snowy Land"
        command:
          - julia --color=yes --project=.buildkite experiments/long_runs/snowy_land.jl
        artifact_paths:
          - "snowy_land_longrun_gpu/*png"
        agents:
          slurm_gpus: 1
          slurm_time: 3:00:00
        env:
          CLIMACOMMS_DEVICE: "CUDA"

      - label: ":snow_capped_mountain: Snowy Land + P Model"
        command:
          - julia --color=yes --project=.buildkite experiments/long_runs/snowy_land_pmodel.jl
        artifact_paths:
          - "snowy_land_pmodel_longrun_gpu/*png"
          - "snowy_land_pmodel_longrun_gpu/*pdf"
        agents:
          slurm_gpus: 1
          slurm_time: 3:00:00
        env:
          CLIMACOMMS_DEVICE: "CUDA"

      - label: ":sunglasses: California regional simulation"
        command:
          - julia --color=yes --project=.buildkite experiments/long_runs/land_region.jl
        artifact_paths: "california_longrun_gpu/*png"
        agents:
          slurm_gpus: 1
          slurm_time: 01:00:00
        env:
          CLIMACOMMS_DEVICE: "CUDA"

      - label: "Soil"
        command:
          - julia --color=yes --project=.buildkite experiments/long_runs/soil.jl
        artifact_paths: "soil_longrun_gpu/*png"
        agents:
          slurm_gpus: 1
          slurm_time: 3:00:00
        env:
          CLIMACOMMS_DEVICE: "CUDA"

      - label: "Global bucket simulation"
        command:
          - julia --color=yes --project=.buildkite experiments/long_runs/bucket.jl
        artifact_paths: "bucket_longrun_gpu/*png"
        agents:
          slurm_gpus: 1
          slurm_time: 00:30:00
        env:
          CLIMACOMMS_DEVICE: "CUDA"

  - group: "Perturbed Low-res Global Land Models"
    if: build.env("PERTURBED_RUN") != null
    steps:

      - label: ":snow_capped_mountain: Low-Res Snowy Land Perturbed Temperature"
        command:
          - julia --color=yes --project=.buildkite experiments/long_runs/low_res_snowy_land_temp.jl
        artifact_paths:
          - "lowres_snowy_land_longrun_temp_gpu/*png"
        agents:
          slurm_gpus: 1
          slurm_time: 3:00:00
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          PERTURBED_RUN: ""
 
      - label: ":snow_capped_mountain: Low-Res Snowy Land Perturbed RH"
        command:
          - julia --color=yes --project=.buildkite experiments/long_runs/low_res_snowy_land_rh.jl
        artifact_paths:
          - "lowres_snowy_land_longrun_rh_gpu/*png"
        agents:
          slurm_gpus: 1
          slurm_time: 3:00:00
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          PERTURBED_RUN: ""

  - group: "Longer runs of Global Land Models"
    if: build.env("LONGER_RUN") != null
    steps:
      - label: "Snowy Land, 19 years"
        command:
          - julia --color=yes --project=.buildkite experiments/long_runs/snowy_land.jl
        artifact_paths:
          - "snowy_land_longrun_gpu/*png"
        agents:
          slurm_gpus: 1
          slurm_time: 15:00:00
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          LONGER_RUN: ""

      - label: "Soil, 20 years"
        command:
          - julia --color=yes --project=.buildkite experiments/long_runs/soil.jl
        artifact_paths: "soil_longrun_gpu/*png"
        agents:
          slurm_gpus: 1
          slurm_time: 15:00:00
        env:
          CLIMACOMMS_DEVICE: "CUDA"
          LONGER_RUN: ""

  - wait

  # To check if the ILAMB leaderboard should be generated or not, we check for
  # the existence of `LONGER_RUN` and `ILAMB_RUN`. If both environment variables
  # exist, then this group step is ran and otherwise, this group step does not
  # run. If you want to generate the ILAMB leaderboard for a twenty year long
  # run, then pass both `LONGER_RUN=""` and `ILAMB_RUN=""` as environment
  # variables on Buildkite when starting a new build.

  - group: "ILAMB leaderboard"
    if: build.env("LONGER_RUN") != null && build.env("ILAMB_RUN") != null
    steps:
    - label: "Set up ILAMB leaderboard"
      command:
        - julia --color=yes --project=.buildkite/ experiments/ilamb/tests/test_ilamb_setup.jl
        - julia --color=yes --project=.buildkite/ experiments/ilamb/ilamb_setup.jl $$ILAMB_DIAG_DIR $$ILAMB_BUILDKITE_DIR $BUILDKITE_BUILD_NUMBER $BUILDKITE_COMMIT
      env:
        ILAMB_DIAG_DIR: "snowy_land_longrun_gpu/global_diagnostics/ILAMB_diagnostics"
        ILAMB_BUILDKITE_DIR: "/net/sampo/data1/ilamb/buildkite"

    - wait

    - label: "Run ILAMB leaderboard"
      command:
        - export PATH="$${ILAMB_ROOT}/ilamb_env/bin:$PATH"
        - ilamb-run --config $$ILAMB_ROOT/buildkite/buildkite_ilamb.cfg --model_root $$ILAMB_ROOT/buildkite/MODELS/ --regions global --build_dir $$ILAMB_ROOT/buildkite/_build
        - tar czf $$ILAMB_ROOT/buildkite/ilamb_leaderboard.tar.gz -C $$ILAMB_ROOT/buildkite _build
      env:
        # This cannot be renamed as the ILAMB software checks for the existence
        # of the `ILAMB_ROOT` environment variable.
        ILAMB_ROOT: "/net/sampo/data1/ilamb"
      artifact_paths:
        - "/net/sampo/data1/ilamb/buildkite/ilamb_leaderboard.tar.gz"
      agents:
        - slurm_mem: 32GB
        - slurm_time: "2:00:00"
      concurrency: 1
      concurrency_group: "ilamb-run"
