agents:
  queue: clima
  slurm_mem: 8G
  modules: climacommon/2025_05_15

env:

# We check for the existence of `LONGER_RUN` to determine whether a `LONGER_RUN`
# of `snowy_land.jl`. If you want to do a very long run on Buildkite manually,
# then make a new build and pass `LONGER_RUN=""` as an environment variable. If
# you want to do a very long run locally, you can enter `export LONGER_RUN=""`
# in the terminal and run
# `julia --color=yes --project=.buildkite experiments/long_runs/snowy_land.jl`.
# In both cases, the value of `LONGER_RUN` does not matter.

steps:
  - label: "init :GPU:"
    key: "init_gpu_env"
    command:
      - echo "--- Instantiate"

      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "ILAMB leaderboard"
    if: build.env("LONGER_RUN") != null && build.env("ILAMB_RUN") != null
    steps:
    - label: "Set up ILAMB leaderboard"
      command:
        - julia --color=yes --project=.buildkite/ experiments/misc/ilamb_setup.jl $$ILAMB_DIAG_DIR $$ILAMB_BUILDKITE_DIR $BUILDKITE_COMMIT
      env:
        # ILAMB_DIAG_DIR: "snowy_land_longrun_gpu/global_diagnostics/ILAMB_diagnostics"
        ILAMB_DIAG_DIR: "/home/kphan2/worktree/ClimaLand.jl/ilamb-script/ilamb_files"
        ILAMB_BUILDKITE_DIR: "/net/sampo/data1/ilamb/buildkite"

    - wait

    - label: "Run ILAMB leaderboard"
      command:
        - export PATH="$${ILAMB_ROOT_DIR}/ilamb_env/bin:$PATH"
        - export ILAMB_ROOT=$$ILAMB_ROOT_DIR
        - ilamb-run --config $$ILAMB_ROOT_DIR/buildkite/buildkite_ilamb.cfg --model_root $$ILAMB_ROOT_DIR/buildkite/MODELS/ --regions global --build_dir $$ILAMB_ROOT_DIR/buildkite/_build
        - tar czf $$ILAMB_ROOT_DIR/buildkite/ilamb_leaderboard.tar.gz -C $$ILAMB_ROOT_DIR/buildkite _build
      env:
        ILAMB_ROOT_DIR: "/net/sampo/data1/ilamb"
      artifact_paths:
        # - "$$ILAMB_ROOT_DIR/buildkite/ilamb_leaderboard.tar.gz"
        - "/net/sampo/data1/ilamb/buildkite/ilamb_leaderboard.tar.gz"
      agents:
        - slurm_mem: 32GB
        - slurm_time: "2:00:00"
      concurrency: 1
      concurrency_group: "ilamb-run"
