# Autogenerated wrapper script for oneTBB_jll for i686-w64-mingw32-cxx03
export libtbb, libtbbmalloc, libtbbmalloc_proxy

JLLWrappers.@generate_wrapper_header("oneTBB")
JLLWrappers.@declare_library_product(libtbb, "libtbb12.dll")
JLLWrappers.@declare_library_product(libtbbmalloc, "libtbbmalloc.dll")
JLLWrappers.@declare_library_product(libtbbmalloc_proxy, "libtbbmalloc_proxy.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtbb,
        "bin\\libtbb12.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtbbmalloc,
        "bin\\libtbbmalloc.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtbbmalloc_proxy,
        "bin\\libtbbmalloc_proxy.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
