# Autogenerated wrapper script for LLVMOpenMP_jll for x86_64-apple-darwin
export libomp

JLLWrappers.@generate_wrapper_header("LLVMOpenMP")
JLLWrappers.@declare_library_product(libomp, "@rpath/libomp.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libomp,
        "lib/libomp.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
