# Autogenerated wrapper script for Libmount_jll for armv7l-linux-musleabihf
export libmount

JLLWrappers.@generate_wrapper_header("Libmount")
JLLWrappers.@declare_library_product(libmount, "libmount.so.1")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmount,
        "lib/libmount.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
