# Autogenerated wrapper script for Pixman_jll for i686-w64-mingw32
export libpixman

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Pixman")
JLLWrappers.@declare_library_product(libpixman, "libpixman-1-0.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libpixman,
        "bin\\libpixman-1-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
