# Autogenerated wrapper script for Bzip2_jll for aarch64-apple-darwin
export libbzip2

JLLWrappers.@generate_wrapper_header("Bzip2")
JLLWrappers.@declare_library_product(libbzip2, "@rpath/libbz2.1.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbzip2,
        "lib/libbz2.1.0.9.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
