# Autogenerated wrapper script for Bzip2_jll for x86_64-unknown-freebsd
export libbzip2

JLLWrappers.@generate_wrapper_header("Bzip2")
JLLWrappers.@declare_library_product(libbzip2, "libbz2.so.1.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbzip2,
        "lib/libbz2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
