# Autogenerated wrapper script for libaec_jll for x86_64-w64-mingw32
export aec, libaec, libsz

JLLWrappers.@generate_wrapper_header("libaec")
JLLWrappers.@declare_library_product(libaec, "libaec.dll")
JLLWrappers.@declare_library_product(libsz, "libsz.dll")
JLLWrappers.@declare_executable_product(aec)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libaec,
        "bin\\libaec.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsz,
        "bin\\libsz.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        aec,
        "bin\\graec.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
