# Autogenerated wrapper script for LAME_jll for armv7l-linux-musleabihf
export lame, libmp3lame

JLLWrappers.@generate_wrapper_header("LAME")
JLLWrappers.@declare_library_product(libmp3lame, "libmp3lame.so.0")
JLLWrappers.@declare_executable_product(lame)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmp3lame,
        "lib/libmp3lame.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        lame,
        "bin/lame",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
