# Autogenerated wrapper script for GettextRuntime_jll for armv7l-linux-gnueabihf-cxx03
export envsubst, gettext, libasprintf, libintl, ngettext

using CompilerSupportLibraries_jll
using Libiconv_jll
JLLWrappers.@generate_wrapper_header("GettextRuntime")
JLLWrappers.@declare_library_product(libasprintf, "libasprintf.so.0")
JLLWrappers.@declare_library_product(libintl, "libintl.so.8")
JLLWrappers.@declare_executable_product(envsubst)
JLLWrappers.@declare_executable_product(gettext)
JLLWrappers.@declare_executable_product(ngettext)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Libiconv_jll)
    JLLWrappers.@init_library_product(
        libasprintf,
        "lib/libasprintf.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libintl,
        "lib/libintl.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        envsubst,
        "bin/envsubst",
    )

    JLLWrappers.@init_executable_product(
        gettext,
        "bin/gettext",
    )

    JLLWrappers.@init_executable_product(
        ngettext,
        "bin/ngettext",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
