# Autogenerated wrapper script for GettextRuntime_jll for x86_64-w64-mingw32-cxx03
export envsubst, gettext, libasprintf, libintl, ngettext

using CompilerSupportLibraries_jll
using Libiconv_jll
JLLWrappers.@generate_wrapper_header("GettextRuntime")
JLLWrappers.@declare_library_product(libasprintf, "libasprintf-0.dll")
JLLWrappers.@declare_library_product(libintl, "libintl-8.dll")
JLLWrappers.@declare_executable_product(envsubst)
JLLWrappers.@declare_executable_product(gettext)
JLLWrappers.@declare_executable_product(ngettext)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Libiconv_jll)
    JLLWrappers.@init_library_product(
        libasprintf,
        "bin\\libasprintf-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libintl,
        "bin\\libintl-8.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        envsubst,
        "bin\\envsubst.exe",
    )

    JLLWrappers.@init_executable_product(
        gettext,
        "bin\\gettext.exe",
    )

    JLLWrappers.@init_executable_product(
        ngettext,
        "bin\\ngettext.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
