# Autogenerated wrapper script for Hwloc_jll for x86_64-w64-mingw32
export libhwloc, lstopo_no_graphics

using XML2_jll
JLLWrappers.@generate_wrapper_header("Hwloc")
JLLWrappers.@declare_library_product(libhwloc, "libhwloc-15.dll")
JLLWrappers.@declare_executable_product(lstopo_no_graphics)
function __init__()
    JLLWrappers.@generate_init_header(XML2_jll)
    JLLWrappers.@init_library_product(
        libhwloc,
        "bin\\libhwloc-15.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        lstopo_no_graphics,
        "bin\\lstopo-no-graphics.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
