# Autogenerated wrapper script for Hwloc_jll for x86_64-apple-darwin
export libhwloc, lstopo_no_graphics

using XML2_jll
JLLWrappers.@generate_wrapper_header("Hwloc")
JLLWrappers.@declare_library_product(libhwloc, "@rpath/libhwloc.15.dylib")
JLLWrappers.@declare_executable_product(lstopo_no_graphics)
function __init__()
    JLLWrappers.@generate_init_header(XML2_jll)
    JLLWrappers.@init_library_product(
        libhwloc,
        "lib/libhwloc.15.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        lstopo_no_graphics,
        "bin/lstopo-no-graphics",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
