# Autogenerated wrapper script for Lz4_jll for x86_64-w64-mingw32
export liblz4, lz4, lz4c, lz4cat, unlz4

JLLWrappers.@generate_wrapper_header("Lz4")
JLLWrappers.@declare_library_product(liblz4, "msys-lz4-1.dll")
JLLWrappers.@declare_executable_product(lz4)
JLLWrappers.@declare_executable_product(lz4c)
JLLWrappers.@declare_executable_product(lz4cat)
JLLWrappers.@declare_executable_product(unlz4)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblz4,
        "bin\\msys-lz4-1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        lz4,
        "bin\\lz4.exe",
    )

    JLLWrappers.@init_executable_product(
        lz4c,
        "bin\\lz4c.exe",
    )

    JLLWrappers.@init_executable_product(
        lz4cat,
        "bin\\lz4cat.exe",
    )

    JLLWrappers.@init_executable_product(
        unlz4,
        "bin\\unlz4.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
