# Autogenerated wrapper script for JpegTurbo_jll for i686-w64-mingw32
export cjpeg, djpeg, jpegtran, libjpeg, libturbojpeg

JLLWrappers.@generate_wrapper_header("JpegTurbo")
JLLWrappers.@declare_library_product(libjpeg, "libjpeg-62.dll")
JLLWrappers.@declare_library_product(libturbojpeg, "libturbojpeg.dll")
JLLWrappers.@declare_executable_product(cjpeg)
JLLWrappers.@declare_executable_product(djpeg)
JLLWrappers.@declare_executable_product(jpegtran)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libjpeg,
        "bin\\libjpeg-62.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libturbojpeg,
        "bin\\libturbojpeg.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        cjpeg,
        "bin\\cjpeg.exe",
    )

    JLLWrappers.@init_executable_product(
        djpeg,
        "bin\\djpeg.exe",
    )

    JLLWrappers.@init_executable_product(
        jpegtran,
        "bin\\jpegtran.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
