# Autogenerated wrapper script for Xorg_xtrans_jll for aarch64-linux-musl
JLLWrappers.@generate_wrapper_header("Xorg_xtrans")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
