# Autogenerated wrapper script for Glib_jll for aarch64-apple-darwin
export libgio, libgirepository, libglib, libgmodule, libgobject, libgthread

using GettextRuntime_jll
using Libffi_jll
using Libiconv_jll
using PCRE2_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("Glib")
JLLWrappers.@declare_library_product(libgio, "@rpath/libgio-2.0.0.dylib")
JLLWrappers.@declare_library_product(libgirepository, "@rpath/libgirepository-2.0.0.dylib")
JLLWrappers.@declare_library_product(libglib, "@rpath/libglib-2.0.0.dylib")
JLLWrappers.@declare_library_product(libgmodule, "@rpath/libgmodule-2.0.0.dylib")
JLLWrappers.@declare_library_product(libgobject, "@rpath/libgobject-2.0.0.dylib")
JLLWrappers.@declare_library_product(libgthread, "@rpath/libgthread-2.0.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(GettextRuntime_jll, Libffi_jll, Libiconv_jll, PCRE2_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libgio,
        "lib/libgio-2.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgirepository,
        "lib/libgirepository-2.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libglib,
        "lib/libglib-2.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgmodule,
        "lib/libgmodule-2.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgobject,
        "lib/libgobject-2.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgthread,
        "lib/libgthread-2.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
