agents:
  queue: clima
  modules: climacommon/2026_02_18 nsight-systems/2024.6.1

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_CUDA_MEMORY_POOL: "cuda"
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100

steps:
  - label: "init environment :computer:"
    key: "init_env"
    concurrency: 1
    concurrency_group: "depot/climaland-benchmark"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate experiments"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.precompile(;strict=true); using CUDA; CUDA.precompile_runtime(); Pkg.status()'"
    agents:
      slurm_gpus: 1
      slurm_nodes: 1
      slurm_ntasks: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait


  - group: "Profile with Nsight"
    steps:
      - label: ":snow_capped_mountain: Snowy Land latest"
        command:
          - mkdir -p snowy_land_benchmark_gpu
          - >
            nsys profile --start-later=true --capture-range=cudaProfilerApi --trace=nvtx,mpi,cuda,osrt --cuda-memory-usage=true --kill=none --output=snowy_land_benchmark_gpu/report_latest
            julia --color=yes --project=.buildkite experiments/benchmarks/snowy_land.jl
        artifact_paths:
          - "snowy_land_benchmark_gpu/report*"
        env:
          CLIMACOMMS_DEVICE: CUDA
          JULIA_NVTX_CALLBACKS: "gc,alloc,free,inference"
          CLIMA_NAME_CUDA_KERNELS_FROM_STACK_TRACE: true
        agents:
          slurm_mem: 64G
          slurm_cpus_per_task: 4
          slurm_gpus: 1
      
      - wait: ~
        continue_on_failure: true

      - label: ":snow_capped_mountain: Snowy Land 52"
        command:
          - "julia --project=.buildkite -e 'using Pkg; Pkg.add(\"ClimaCore\"; version=0.14.52); Pkg.instantiate(;verbose=true)'"
          - >
            nsys profile --start-later=true --capture-range=cudaProfilerApi --trace=nvtx,mpi,cuda,osrt --cuda-memory-usage=true --kill=none --output=snowy_land_benchmark_gpu/report_52
            julia --color=yes --project=.buildkite experiments/benchmarks/snowy_land.jl
        artifact_paths:
          - "snowy_land_benchmark_gpu/report*"
        env:
          CLIMACOMMS_DEVICE: CUDA
          JULIA_NVTX_CALLBACKS: "gc,alloc,free,inference"
          CLIMA_NAME_CUDA_KERNELS_FROM_STACK_TRACE: true
        agents:
          slurm_mem: 64G
          slurm_cpus_per_task: 4
          slurm_gpus: 1

      - wait: ~
        continue_on_failure: true
      - label: ":snow_capped_mountain: Snowy Land 51"
        command:
          - "julia --project=.buildkite -e 'using Pkg; Pkg.add(\"ClimaCore\"; version=0.14.51); Pkg.instantiate(;verbose=true)'"
          - >
            nsys profile --start-later=true --capture-range=cudaProfilerApi --trace=nvtx,mpi,cuda,osrt --cuda-memory-usage=true --kill=none --output=snowy_land_benchmark_gpu/report_51
            julia --color=yes --project=.buildkite experiments/benchmarks/snowy_land.jl
        artifact_paths:
          - "snowy_land_benchmark_gpu/report*"
        env:
          CLIMACOMMS_DEVICE: CUDA
          JULIA_NVTX_CALLBACKS: "gc,alloc,free,inference"
          CLIMA_NAME_CUDA_KERNELS_FROM_STACK_TRACE: true
        agents:
          slurm_mem: 64G
          slurm_cpus_per_task: 4
          slurm_gpus: 1

      - wait: ~
        continue_on_failure: true
      - label: ":snow_capped_mountain: Snowy Land 50"
        command:
          - "julia --project=.buildkite -e 'using Pkg; Pkg.add(\"ClimaCore\"; version=0.14.50); Pkg.instantiate(;verbose=true)'"
          - >
            nsys profile --start-later=true --capture-range=cudaProfilerApi --trace=nvtx,mpi,cuda,osrt --cuda-memory-usage=true --kill=none --output=snowy_land_benchmark_gpu/report_50
            julia --color=yes --project=.buildkite experiments/benchmarks/snowy_land.jl
        artifact_paths:
          - "snowy_land_benchmark_gpu/report*"
        env:
          CLIMACOMMS_DEVICE: CUDA
          JULIA_NVTX_CALLBACKS: "gc,alloc,free,inference"
          CLIMA_NAME_CUDA_KERNELS_FROM_STACK_TRACE: true
        agents:
          slurm_mem: 64G
          slurm_cpus_per_task: 4
          slurm_gpus: 1

      - wait: ~
        continue_on_failure: true
      - label: ":snow_capped_mountain: Snowy Land 502"
        command:
          - "julia --project=.buildkite -e 'using Pkg; Pkg.add(\"ClimaCore\"; version=0.14.50); Pkg.instantiate(;verbose=true)'"
          - >
            nsys profile --start-later=true --capture-range=cudaProfilerApi --trace=nvtx,mpi,cuda,osrt --cuda-memory-usage=true --kill=none --output=snowy_land_benchmark_gpu/report_502
            julia --color=yes --project=.buildkite experiments/benchmarks/snowy_land.jl
        artifact_paths:
          - "snowy_land_benchmark_gpu/report*"
        env:
          CLIMACOMMS_DEVICE: CUDA
          JULIA_NVTX_CALLBACKS: "gc,alloc,free,inference"
          CLIMA_NAME_CUDA_KERNELS_FROM_STACK_TRACE: false
        agents:
          slurm_mem: 64G
          slurm_cpus_per_task: 4
          slurm_gpus: 1
