agents:
  queue: clima
  modules: climacommon/2025_03_18

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1

steps:
  - label: "init environment :computer:"
    key: "init_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate experiments"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.status()'"
    agents:
      slurm_ntasks: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait


  - group: "Target Benchmark"
    steps:

      - label: ":snow_capped_mountain: Snowy Land"
        command: "julia --color=yes --project=.buildkite experiments/benchmarks/snowy_land.jl --profiler flamegraph"
        artifact_paths:
          - "snowy_land_benchmark_cpu/flame*html"
        env:
           CLIMACOMMS_DEVICE: CPU
        agents:
          slurm_mem: 8GB
