agents:
  queue: clima
  modules: climacommon/2025_03_18 nsight-systems/2024.6.1

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  JULIA_NVTX_CALLBACKS: "gc,alloc,free,inference"
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_CUDA_MEMORY_POOL: "cuda"

steps:
  - label: "init environment :computer:"
    key: "init_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate experiments"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.status()'"
    agents:
      slurm_gpus: 1
      slurm_ntasks: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  # - group: "Benchmark (CPU)"
  #   steps:
  #     - label: ":bucket: Bucket (CPU)"
  #       command: "julia --color=yes --project=.buildkite experiments/benchmarks/bucket.jl"
  #       env:
  #         CLIMACOMMS_DEVICE: CPU
  #       agents:
  #         slurm_mem: 8GB
  #       artifact_paths:
  #         - "bucket_benchmark_cpu/flame*html"

  #     - label: ":droplet: RichardsModel (CPU)"
  #       command: "julia --color=yes --project=.buildkite experiments/benchmarks/richards.jl"
  #       env:
  #         CLIMACOMMS_DEVICE: CPU
  #       agents:
  #         slurm_mem: 8GB
  #       artifact_paths:
  #           - "richards_benchmark_cpu/flame*html"

  #     - label: ":snow_capped_mountain: Snowy Land (CPU)"
  #       command: "julia --color=yes --project=.buildkite experiments/benchmarks/snowy_land.jl"
  #       env:
  #         CLIMACOMMS_DEVICE: CPU
  #       agents:
  #         slurm_mem: 8GB
  #       artifact_paths:
  #           - "snowy_land_benchmark_cpu/flame*html"

  - group: "Target Benchmark (GPU)"
    steps:
      # - label: "compare long"
      #   command: "julia --color=yes --project=.buildkite experiments/benchmarks/cb_comparison.jl"
      #   env:
      #     CLIMACOMMS_DEVICE: CUDA
      #   agents:
      #     slurm_mem: 8GB
      #     slurm_gpus: 1

      # - label: ":bucket: Bucket"
      #   command: "julia --color=yes --project=.buildkite experiments/benchmarks/bucket.jl"
      #   env:
      #     CLIMACOMMS_DEVICE: CUDA
      #   agents:
      #     slurm_mem: 8GB
      #     slurm_gpus: 1

      # - label: ":droplet: RichardsModel"
      #   command: "julia --color=yes --project=.buildkite experiments/benchmarks/richards.jl"
      #   env:
      #     CLIMACOMMS_DEVICE: CUDA
      #   agents:
      #     slurm_mem: 8GB
      #     slurm_gpus: 1

      - label: ":snow_capped_mountain: Snowy Land"
        command: "julia --color=yes --project=.buildkite experiments/benchmarks/snowy_land.jl"
        env:
          CLIMACOMMS_DEVICE: CUDA
        agents:
          slurm_mem: 8GB
          slurm_gpus: 1

      # - label: ":no_entry_sign: :evergreen_tree: Soil"
      #   command: "julia --color=yes --project=.buildkite experiments/benchmarks/soil.jl"
      #   env:
      #     CLIMACOMMS_DEVICE: CUDA
      #   agents:
      #     slurm_mem: 8GB
      #     slurm_gpus: 1

  - group: "Profile with Nsight"
    steps:
      - label: ":snow_capped_mountain: Snowy Land"
        command:
          - mkdir -p snowy_land_benchmark_gpu
          - >
            nsys profile --start-later=true --capture-range=cudaProfilerApi --kill=none --trace=nvtx,mpi,cuda,osrt --output=snowy_land_benchmark_gpu/report
            julia --color=yes --project=.buildkite experiments/benchmarks/snowy_land.jl --profiler nsight
        artifact_paths:
          - "snowy_land_benchmark_gpu/report*"
        env:
          CLIMACOMMS_DEVICE: CUDA
        agents:
          slurm_mem: 64G
          slurm_cpus_per_task: 8
          slurm_gpus: 1

      # - label: ":no_entry_sign: :evergreen_tree: Soil"
      #   command:
      #     - mkdir -p soil_benchmark_gpu
      #     - >
      #       nsys profile --start-later=true  --capture-range=cudaProfilerApi --kill=none --trace=nvtx,mpi,cuda,osrt --output=soil_benchmark_gpu/report
      #       julia --color=yes --project=.buildkite experiments/benchmarks/soil.jl --profiler nsight
      #   artifact_paths:
      #     - "soil_benchmark_gpu/report*"
      #   env:
      #     CLIMACOMMS_DEVICE: CUDA
      #   agents:
      #     slurm_mem: 64G
      #     slurm_cpus_per_task: 8
      #     slurm_gpus: 1
