agents:
  queue: clima
  modules: climacommon/2024_12_16

env:
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  JULIA_NVTX_CALLBACKS: gc
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_CUDA_MEMORY_POOL: "cuda"

steps:
  - label: "init environment :computer:"
    key: "init_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate project"
      - "julia --project -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate experiments"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.develop(;path=\".\"); Pkg.instantiate(;verbose=true)'"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.status()'"
    agents:
      slurm_gpus: 1
      slurm_ntasks: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8

  - wait

  - group: "Target Benchmark"
    steps:
      - label: ":bucket: Bucket"
        command: "julia --color=yes --project=.buildkite experiments/benchmarks/bucket.jl"
        artifact_paths:
          - "bucket_benchmark_gpu/*html"
        env:
          CLIMACOMMS_DEVICE: CUDA
        agents:
          slurm_mem: 8GB
          slurm_gpus: 1

      - label: ":droplet: RichardsModel"
        command: "julia --color=yes --project=.buildkite experiments/benchmarks/richards.jl"
        artifact_paths:
          - "richards_benchmark_gpu/*html"
        env:
          CLIMACOMMS_DEVICE: CUDA
        agents:
          slurm_mem: 8GB
          slurm_gpus: 1

      - label: ":seedling: Soil/Canopy"
        command: "julia --color=yes --project=.buildkite experiments/benchmarks/land.jl"
        artifact_paths:
          - "land_benchmark_gpu/*html"
        env:
          CLIMACOMMS_DEVICE: CUDA
        agents:
          slurm_mem: 8GB
          slurm_gpus: 1

      - label: ":snow_capped_mountain: Snowy Land"
        command: "julia --color=yes --project=.buildkite experiments/benchmarks/snowy_land.jl"
        artifact_paths:
          - "snowy_land_benchmark_gpu/*html"
        env:
          CLIMACOMMS_DEVICE: CUDA
        agents:
          slurm_mem: 8GB
          slurm_gpus: 1
