name: ClimaLandSimulations CI
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read

jobs:
  lib-climalandsimulations:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    strategy:
      matrix:
        version:
          - '1.10'
          - '1.11'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - name: Install Julia dependencies
        run: >
          julia --project=lib/ClimaLandSimulations -e 'using Pkg; Pkg.develop(path=".")'
      - name: Run the tests
        continue-on-error: true
        env:
            CI_OUTPUT_DIR: output
        run: >
          julia --project=lib/ClimaLandSimulations -e 'using Pkg; Pkg.test("ClimaLandSimulations")'
