name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11'
      - name: Cache Julia depot
        uses: actions/cache@v4
        with:
          # Cache Julia's depot
          path: |
            ~/.julia/packages
            ~/.julia/compiled
            ~/.julia/artifacts
            ~/.julia/scratchspaces
            ~/.julia/registries
            ~/.julia/logs
          # The cache key includes the OS, Julia version, and the project's dependencies
          key: ${{ matrix.os }}-julia-${{ matrix.version }}-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
          # Fallback keys to use if the primary key isn't found
          restore-keys: |
            ${{ matrix.os }}-julia-${{ matrix.version }}-
            ${{ matrix.os }}-julia-
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.precompile()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --color=yes --project=docs/ --procs=4 docs/make.jl
