name: JuliaFormatter

on:
  push:
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v5

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          julia_file_change:
            - added|modified: '**.jl'
    - uses: julia-actions/setup-julia@latest
      if: steps.filter.outputs.julia_file_change == 'true'
      with:
        version: '1.11'

    - name: Apply JuliaFormatter
      if: steps.filter.outputs.julia_file_change == 'true'
      run: |
        julia --project=.dev .dev/climaformat.jl .

    - name: Check formatting diff
      if: steps.filter.outputs.julia_file_change == 'true'
      run: |
        git diff --color=always --exit-code
