name: JuliaFormatter

on:
  push:
    tags: '*'
  pull_request:
  merge_group:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@v4
        with:
          version: '1' # Set `version` to '1.0.62' if you run into issues
          # To use the same JuliaFormatter version locally, run: `julia -e 'using Pkg; Pkg.add(PackageSpec("JuliaFormatter", v"1.0.62"))'`
          suggestion-label: 'format-suggest' # leave this unset or empty to show suggestions for all PRs
